version: '3.7'
services:
  panoptes-dev-env:
    image: panoptes-utils:developer
    tty: true
    container_name: panoptes-jupyter-lab
    privileged: true
    network_mode: host
    environment:
      # These need to be defined in the shell on the host.
      PANDIR:
      PANLOG:
      PANOPTES_CONFIG_HOST:
      PANOPTES_CONFIG_PORT:
      PANOPTES_CONFIG_FILE:
    ports:
      # JupyterLab
      - "${JUPYTER_PORT:-8080}:8080"
    restart: on-failure
    volumes:
      - type: bind
        source: ../
        target: /var/panoptes/panoptes-utils
    command: [ "jupyter-lab --no-browser --port ${JUPYTER_PORT:-8080}" ]

