steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'amd64'
  args:
  - 'build'
  - '--tag=gcr.io/${PROJECT_ID}/panoptes-utils:amd64'
  - '.'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-amd64'
  args:
  - 'push'
  - 'gcr.io/${PROJECT_ID}/panoptes-utils:amd64'
  waitFor: ['amd64']
- name: 'gcr.io/cloud-builders/docker'
  id: 'arm'
  args:
  - 'build'
  - '--tag=gcr.io/${PROJECT_ID}/panoptes-utils:arm'
  - '.'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-arm'
  args:
  - 'push'
  - 'gcr.io/${PROJECT_ID}/panoptes-utils:arm'
  waitFor: ['arm']

- name: 'gcr.io/cloud-builders/docker'
  id: 'manifest'
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  args:
  - 'manifest'
  - 'create'
  - 'gcr.io/${PROJECT_ID}/panoptes-utils:arm32v7'
  - 'gcr.io/${PROJECT_ID}/panoptes-utils:amd64' 
  waitFor: ['push-amd64', 'push-arm']

- name: 'gcr.io/cloud-builders/docker'
  id: 'annotate-manifest'
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  args:
  - 'manifest'
  - 'annotate'
  - 'gcr.io/${PROJECT_ID}/panoptes-utils:arm32v7'
  - '--os=linux'
  - '--arch=arm'
  waitFor: ['manifest']

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-manifest'
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  args:
  - 'manifest'
  - 'push'
  - 'gcr.io/${PROJECT_ID}/panoptes-utils:$COMMIT_SHA'
  waitFor: ['annotate-manifest']


images:
  - 'gcr.io/${PROJECT_ID}/panoptes-utils:amd64'
  - 'gcr.io/${PROJECT_ID}/panoptes-utils:arm32v7'
