name: panoptes-env
channels:
  - rpi
  - astropy
dependencies:
  - python=3
  - astropy
  - cffi
  - ipywidgets
  - jupyter_console
  - jupyterlab
  - libffi
  - matplotlib
  - numpy
  - pip
  - psutil
  - pyyaml
  - pyzmq
  - readline
  - scikit-image
  - scikit-learn
  - scipy
  - tornado
  - zeromq
  - pip:
    - -r requirements.txt
    - -e ".[all]"
