name: panoptes-env
channels:
  - astropy
  - conda-forge
dependencies:
  - python=3
  - astropy
  - cffi
  - Flask
  - google-cloud-storage
  - jupyter_console
  - libffi
  - matplotlib-base
  - numpy
  - pip
  - psycopg2
  - pyserial
  - python-dateutil
  - PyYAML
  - pyzmq
  - readline
  - scikit-image
  - scikit-learn
  - scipy
  - tornado
  - zeromq
  - pip:
    - astroplan
    - ruamel-yaml
    - scalpl

