name: panoptes-env
channels:
  - rpi
dependencies:
  - python=3
  - astropy
  - numpy
  - scipy
  - jupyterlab
  - zeromq
  - pyzmq
  - pyyaml
  - tornado
  - readline
  - scipy
  - scikit-image
  - scikit-learn
  - psutil
  - pip:
    - -r /var/panoptes/panoptes-utils/requirements.txt
