name: panoptes-env
channels:
  - rpi
dependencies:
  - astropy
  - jupyterlab
  - numpy
  - psutil
  - python=3
  - pyyaml
  - pyzmq
  - readline
  - scikit-image
  - scikit-learn
  - scipy
  - tornado
  - zeromq
  - pip:
    - -r /var/panoptes/panoptes-utils/requirements.txt
    - -e ".[all]"