name: panoptes-env
channels:
  - rpi
  - astropy
dependencies:
  - python=3
  - astropy
  - cffi
  - libffi
  - matplotlib
  - numpy
  - pip
  - pyyaml
  - pyzmq
  - readline
  - scikit-image
  - scikit-learn
  - scipy
  - tornado
  - zeromq
