name: panoptes
channels:
  - astropy
  - conda-forge
dependencies:
  - astroplan>=0.6
  - astropy>=4.0.0
  - codecov
  - coverage
  - coveralls
  - Flask
  - ipython
  - loguru
  - matplotlib-base>=3.0.0
  - numpy
  - photutils
  - pip
  - pycodestyle
  - pyserial
  - pytest-cov
  - pytest-remotedata>=0.3.1
  - pytest
  - python-dateutil
  - python-json-logger
  - PyYAML
  - pyzmq
  - readline
  - requests
  - ruamel.yaml>=0.15
  - scikit-image
  - scipy
  - tweepy
  - versioneer
  - zeromq
  - pip:
    - scalpl
    - mocket
