version: '3.2'
services:
  config-server:
    image: gcr.io/panoptes-survey/panoptes-utils
    container_name: config_server
    privileged: true
    network_mode: host
    env_file: 
      - ${PANDIR}/env_file
    volumes:
      - pandir:/var/panoptes
    command: bash -c "/opt/conda/envs/panoptes-env/bin/python ${POCS}/scripts/run_config_server.py --public"
  messaging-hub:
    image: gcr.io/panoptes-survey/panoptes-utils
    container_name: messaging-hub
    privileged: true
    network_mode: host
    env_file: ${PANDIR}/env_file
    depends_on:
      - "config-server"        
    volumes:
      - pandir:/var/panoptes
    command: bash -c "/opt/conda/envs/panoptes-env/bin/python ${POCS}/scripts/run_messaging_hub.py --from-config"
  peas-shell:
    image: gcr.io/panoptes-survey/panoptes-utils
    container_name: peas-shell
    privileged: true
    network_mode: host
    env_file: ${PANDIR}/env_file
    depends_on:
      - "messaging-hub"  
    volumes:
      - pandir:/var/panoptes
    command: /usr/bin/byobu new-session -s "POCS-Session" "/opt/conda/envs/panoptes-env/bin/python ${POCS}/scripts/peas-shell.py"
volumes:
    pandir:
      driver: local
      driver_opts:
        type: none
        device: /var/panoptes
        o: bind

