# PANOPTES development container

FROM arm32v7/python:3.7-slim-stretch AS build-env
MAINTAINER Developers for PANOPTES project<https://github.com/panoptes/POCS>

ARG pan_dir=/var/panoptes

ENV ENV /root/.bashrc
ENV PANDIR $pan_dir
ENV PANLOG $PANDIR/logs 
ENV POCS $PANDIR/POCS  
ENV PANUSER root
ENV SOLVE_FIELD=/usr/bin/solve-field

WORKDIR ${PANDIR}/panoptes-utils/
COPY . ${PANDIR}/panoptes-utils/

RUN rm /bin/sh && ln -s /bin/bash /bin/sh \
    && 

CMD ["python"]  