name: base
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.7
  - Flask
  - PyYAML
  - astroplan
  - astropy
  - click
  - gevent
  - loguru
  - matplotlib
  - numpy
  - pandas
  - photutils
  - pillow
  - python-dateutil
  - readline
  - requests
  - ruamel.yaml
  - scalpl
  - scipy
