steps:
# Set up multiarch support
- name: 'gcr.io/cloud-builders/docker'
  id: 'register-qemu'
  args:
  - 'run'
  - '--privileged'
  - 'multiarch/qemu-user-static:register'
  - '--reset'
  waitFor: ['-']

# Build
# AMD Build
- name: 'gcr.io/cloud-builders/docker'
  id: 'amd64-base'
  args:
  - 'build'
  - '-f=docker/Dockerfile'
  - '--build-arg=base_image=continuumio/miniconda3'
  - '--tag=gcr.io/${PROJECT_ID}/panoptes-base:amd64'
  - '.'
  waitFor: ['register-qemu']
# ARM Build (e.g. Raspberry Pi)
- name: 'gcr.io/cloud-builders/docker'
  id: 'arm32v7-base'
  args:
  - 'build'
  - '-f=docker/Dockerfile'
  - '--build-arg=base_image=balenalib/armv7hf-ubuntu-python:3-latest-run'
  - '--tag=gcr.io/${PROJECT_ID}/panoptes-base:arm32v7'
  - '.'
  waitFor: ['register-qemu']

# Push
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-amd64-base'
  args:
  - 'push'
  - 'gcr.io/${PROJECT_ID}/panoptes-base:amd64'
  waitFor: ['amd64-base']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-arm-base'
  args:
  - 'push'
  - 'gcr.io/${PROJECT_ID}/panoptes-base:arm32v7'
  waitFor: ['arm32v7-base']

# Manifest file for multiarch
- name: 'gcr.io/cloud-builders/docker'
  id: 'manifest-base'
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  args:
  - 'manifest'
  - 'create'
  - 'gcr.io/${PROJECT_ID}/panoptes-base:latest'
  - 'gcr.io/${PROJECT_ID}/panoptes-base:arm32v7'
  - 'gcr.io/${PROJECT_ID}/panoptes-base:amd64'
  waitFor: ['push-amd64-base', 'push-arm-base']

- name: 'gcr.io/cloud-builders/docker'
  id: 'annotate-manifest'
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  args:
  - 'manifest'
  - 'annotate'
  - 'gcr.io/${PROJECT_ID}/panoptes-base:latest'
  - 'gcr.io/${PROJECT_ID}/panoptes-base:arm32v7'
  - '--os=linux'
  - '--arch=arm'
  waitFor: ['manifest-base']

# Push manifest file
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-manifest-base'
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
  args:
  - 'manifest'
  - 'push'
  - 'gcr.io/${PROJECT_ID}/panoptes-base:latest'
  waitFor: ['annotate-manifest']
images:
  - 'gcr.io/${PROJECT_ID}/panoptes-base:amd64'
  - 'gcr.io/${PROJECT_ID}/panoptes-base:arm32v7'
