version: '3.7'
services:
  develop-env:
    image: gcr.io/panoptes-exp/panoptes-utils:develop
    init: true
    container_name: develop-env
    privileged: true
    network_mode: host
    env_file: $PANDIR/.env
    volumes:
      - pandir:/var/panoptes
volumes:
    pandir:
      driver: local
      driver_opts:
        type: none
        device: /var/panoptes
        o: bind

