version: '3.7'
services:
  config-server:
    image: panoptes-utils:develop
    tty: true
    container_name: panoptes-config-server
    env_file:
      - ../tests/env
    network_mode: host
    volumes:
      - working_dir:/var/panoptes/panoptes-utils
      - log_dir:/var/panoptes/panoptes-utils
    command: [ "panoptes-config-server --verbose run --no-save-local --no-load-local" ]

  pytest-testing:
    image: panoptes-utils:develop
    tty: true
    container_name: panoptes-pytest
    depends_on:
      - "config-server"
    env_file:
      - ../tests/env
    network_mode: host
    volumes:
      - working_dir:/var/panoptes/panoptes-utils
      - log_dir:/var/panoptes/panoptes-utils
    command: [ "/var/panoptes/panoptes-utils/scripts/testing/run-tests.sh && panoptes-config-server stop" ]
volumes:
  working_dir:
    driver: local
    driver_opts:
      type: none
      device: /var/panoptes/panoptes-utils
      o: bind
  log_dir:
    driver: local
    driver_opts:
      type: none
      device: /var/panoptes/logs
      o: bind
