version: '3.7'
services:
  panoptes-config-server:
    image: panoptes-utils:develop
    tty: true
    container_name: panoptes-config-server
    env_file:
      - ../tests/env
    volumes:
      - tempdir:/var/panoptes/logs
    command: [ "panoptes-config-server --verbose run --no-save-local --no-load-local" ]

  pytest-testing:
    image: panoptes-utils:develop
    tty: true
    container_name: panoptes-pytest
    depends_on:
      - "panoptes-config-server"
    env_file:
      - ../tests/env
    volumes:
      - tempdir:/var/panoptes/logs
    command:
      - "scripts/wait-for-it.sh"
      - "panoptes-config-server:8765"
      - "--"
      - "/var/panoptes/panoptes-utils/scripts/testing/run-tests.sh"
      - "&&"
      - "panoptes-config-server"
      - "stop"
volumes:
  tempdir:
    driver: local
    driver_opts:
      type: none
      device: ./tmp
      o: bind
