version: '3.7'
services:
  panoptes-config-server:
    image: panoptes-utils:develop
    tty: true
    container_name: panoptes-config-server
    expose:
      - 8765
    env_file:
      - ../tests/env
    volumes:
      - type: bind
        # Relative to docker-compose file.
        source: ../logs
        target: /var/panoptes/logs      
    command: [ "panoptes-config-server --verbose run --no-save-local --no-load-local" ]

  pytest-testing:
    image: panoptes-utils:develop
    tty: true
    container_name: panoptes-pytest
    depends_on:
      - "panoptes-config-server"
    env_file:
        # Relative to docker-compose file.
      - ../tests/env
    volumes:
      - type: bind
        # Relative to docker-compose file.
        source: ../logs
        target: /var/panoptes/logs

    command: [ "/var/panoptes/panoptes-utils/scripts/testing/run-tests.sh && panoptes-config-server stop" ]
