# zshrc file for panoptes docker images.
#
# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="spaceship"

source $ZSH/oh-my-zsh.sh

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=true

plugins=(
  sudo
  git
  dotenv
  zsh-autosuggestions
  history-substring-search
)

export EDITOR='nano'

# Each byobu shell has it's own history
unsetopt share_history

# Spaceship theme
SPACESHIP_USER_PREFIX="Docker user: "
SPACESHIP_USER_SHOW=always
SPACESHIP_HOST_SHOW=always
SPACESHIP_HOST_PREFIX="Service: "
SPACESHIP_TIME_SHOW=true

SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  host          # Hostname section
  user          # Username section
  dir           # Current directory section
  git           # Git section (git_branch + git_status)
  conda         # conda virtualenv section
  exec_time     # Execution time
  line_sep      # Line break
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# Add POCS items
export PATH="$PANDIR/bin:$PANDIR/panoptes-utils/bin:$HOME/bin:/usr/local/bin:$PATH"

# PANOPTES related
export PANDIR=/var/panoptes
